# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Midwestern Robotics Design Competition
email_comm: mrdc@lists.illinois.edu
email_teams: mrdc-teams-l@lists.illinois.edu
email_teams_signup: https://lists.illinois.edu/lists/sigrequest/mrdc-teams-l
google_drive: https://drive.google.com/drive/u/0/folders/0Bwo3CMq0xEayQ2VzSWpBaTRnUGs
facebook: https://www.facebook.com/EOHMRDC/

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mrdc.ec.illinois.edu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# theme: minima
exclude:
 - bower_components
 - bower.json
 - Gemfile
 - Gemfile.lock

gems: 
 - jekyll-assets

assets:
  
  assets:
    - "*.png"
    - "*.jpg"
    - "main.css"
    - "bootstrap.js"

  sources:
    - _assets/css
    # - _assets/images
    # - _assets/javascripts
    # - _assets/stylesheets
    # - _assets/fonts
    - _assets/img
    - _assets/js
    - _assets/bower

  #
